routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ------------------------------------------------------------ 
// ------------------------------------------------------------ Alumni Landing Page
// ------------------------------------------------------------ 

Route::group(['as'=>'alumnihome.'], function() {

	Route::get('/', function () {
	    return view('home.alumni-index');
	})->name('index');

	Route::get('/about-us', function () {
	    return view('home.alumni-aboutus');
	})->name('aboutus');

	Route::get('/event', function () {
	    return view('home.alumni-event');
	})->name('event');

	Route::get('/contact-us', function () {
	    return view('home.alumni-contactus');
	})->name('contactus');

});

// ------------------------------------------------------------ 
// ------------------------------------------------------------ Employer Landing Page
// ------------------------------------------------------------ 

Route::group(['prefix'=>'employer', 'as'=>'employerhome.'], function() {

	Route::get('/index', function () {
	    return view('home.employer-index');
	})->name('index');

	Route::get('/features', function () {
	    return view('home.employer-features');
	})->name('features');

	Route::get('/job-board', function () {
	    return view('home.employer-jobboard');
	})->name('jobboard');

	Route::get('/faqs', function () {
	    return view('home.employer-faqs');
	})->name('faqs');
});

// ------------------------------------------------------------
// ------------------------------------------------------------ Alumni
// ------------------------------------------------------------

// ------------------------------ Login

Auth::routes();

// ------------------------------ Index (Dashboard)

Route::get('/index', [
	'as'=>'alumnidashboard',
	'uses'=>'AlumniController@index'
])->middleware(['alumni', 'auth']);


// ------------------------------ Profile

Route::group(['prefix'=>'a/profile', 'as'=>'alumniprofile.', 'middleware'=>['alumni', 'auth']], function () {
	
	// -------------------- General

	// View Profile
	Route::get('/', [
		'as'=>'view',
		'uses'=>'AlumniController@viewprofile'
	]);

    // View Edit Profile (For New Register User)
	Route::get('/edit', [
		'as'=>'edit',
		'uses'=>'AlumniController@editprofile'
	]);

    // Update Profile (For New Register User)
	Route::post('/update', [
		'as'=>'update',
		'uses'=>'AlumniController@updateprofile'
	]);

	// -------------------- Personal Info

	// View Edit Personal Info
	Route::get('/edit/personal-info', [
		'as'=>'edit.info', 
		'uses'=>'AlumniController@editinfo'
	]);

	// Update Personal Info
	Route::post('/update/personal-info', [
		'as'=>'update.info', 
		'uses'=>'AlumniController@updateinfo'
	]);

	// -------------------- About Me

	// View Edit About Me
	Route::get('/edit/about-me', [
		'as'=>'edit.about', 
		'uses'=>'AlumniController@editabout'
	]);

	// Update About Me
	Route::post('/update/about-me', [
		'as'=>'update.about', 
		'uses'=>'AlumniController@updateabout'
	]);

	// -------------------- Working Experience

	// View Working Experience
	Route::get('/edit/working-experience', [
		'as'=>'view.work', 
		'uses'=>'AlumniController@viewwork'
	]);

	// View Add Working Experience
	Route::get('/add/working-experience', [
		'as'=>'add.work', 
		'uses'=>'AlumniController@addwork'
	]);

	// Save Working Experience
	Route::post('/save/working-experience', [
		'as'=>'save.work', 
		'uses'=>'AlumniController@savework'
	]);

	// View Edit Working Experience
	Route::get('/edit/working-experience/{id}', [
		'as'=>'edit.work', 
		'uses'=>'AlumniController@editwork'
	]);

	// Update Working Experience
	Route::post('/update/working-experience', [
		'as'=>'update.work', 
		'uses'=>'AlumniController@updatework'
	]);

	// Delete Working Experience
	Route::get('/delete/working-experience/{id}', [
		'as'=>'delete.work', 
		'uses'=>'AlumniController@deletework'
	]);

	// -------------------- Education

	// View Education
	Route::get('/edit/education', [
		'as'=>'view.edu', 
		'uses'=>'AlumniController@viewedu'
	]);

	// View Add Education
	Route::get('/add/education', [
		'as'=>'add.edu', 
		'uses'=>'AlumniController@addedu'
	]);

	// Save Education
	Route::post('/save/education', [
		'as' =>'save.edu',
		'uses' =>'AlumniController@saveedu',
	]);

	// View Edit Education
	Route::get('/edit/education/{id}', [
		'as'=>'edit.edu', 
		'uses'=>'AlumniController@editedu'
	]);

	// Update Education
	Route::post('/update/education', [
		'as' =>'update.edu',
		'uses' =>'AlumniController@updateedu'
	]);

	// Delete Education
	Route::get('/delete/education/{id}', [
		'as'=>'delete.edu', 
		'uses'=>'AlumniController@deleteedu'
	]);

	// -------------------- Skills

	// View Skills
	Route::get('/edit/skills-and-expertise', [
		'as'=>'view.skills', 
		'uses'=>'AlumniController@viewskill'
	]);

	// View Add Skills
	Route::get('/add/skills-and-expertise', [
		'as'=>'add.skills', 
		'uses'=>'AlumniController@addskill'
	]);

	// Save Skills
	Route::post('/save/skills-and-expertise', [
		'as'=>'save.skills', 
		'uses'=>'AlumniController@saveskill'
	]);

	// View Edit Skills
	Route::get('/edit/skills-and-expertise/{id}', [
		'as'=>'edit.skills', 
		'uses'=>'AlumniController@editskill'
	]);

	// Update Skills
	Route::post('/update/skills-and-expertise', [
		'as'=>'update.skills', 
		'uses'=>'AlumniController@updateskill'
	]);

	// Delete Skills
	Route::get('/delete/skills-and-expertise/{id}', [
		'as' =>'delete.skills',
		'uses'=>'AlumniController@deleteskill'
	]);

	// -------------------- Language

	// View Language
	Route::get('/edit/language', [
		'as'=>'view.lang', 
		'uses'=>'AlumniController@viewlang'
	]);

	// View Add Language
	Route::get('/add/language', [
		'as'=>'add.lang', 
		'uses'=>'AlumniController@addlang'
	]);

	// Save Language
	Route::post('/save/language', [
		'as'=>'save.lang', 
		'uses'=>'AlumniController@savelang'
	]);

	// View Edit Language
	Route::get('/edit/language/{id}', [
		'as'=>'edit.lang', 
		'uses'=>'AlumniController@editlang'
	]);

	// Update Language
	Route::post('/update/language', [
		'as'=>'update.lang', 
		'uses'=>'AlumniController@updatelang'
	]);

	// Delete Language
	Route::get('/delete/language/{id}', [
		'as'=>'delete.lang', 
		'uses'=>'AlumniController@deletelang'
	]);

});


// ------------------------------ Setting

Route::group(['prefix'=>'a/setting', 'as'=>'alumnisetting.', 'middleware'=>['alumni', 'auth']], function () {

	// View Setting
	Route::get('/', ['as'=>'view', 'uses'=>'AlumniController@viewsetting']);

	// View Edit Setting
	Route::get('/edit', ['as'=>'edit', 'uses'=>'AlumniController@editsetting']);

	// Update Setting
	Route::post('/edit', ['as'=>'update', 'uses'=>'AlumniController@updatesetting']);

	// View Edit Password
	Route::get('/change-password', ['as'=>'changepassword', 'uses'=>'AlumniController@editpassword']);

	// Update Password
	Route::post('/change-password', ['as'=>'updatepassword', 'uses'=>'AlumniController@updatepassword']);

});


// ------------------------------------------------------------
// ------------------------------------------------------------ Employer
// ------------------------------------------------------------

// ------------------------------ Login / Register

Route::group(['prefix'=>'e', 'as'=>'employer.', 'middleware'=>['guest']], function() {

	Route::get('/login', function () {
	    return view('auth.employer-login');
	})->name('login');

	Route::get('/register', function () {
	    return view('auth.employer-register');
	})->name('register');

	Route::get('/password/request', function () {
	    return view('auth.passwords.employer-email');
	})->name('password.request');

	Route::get('/password/reset', function () {
	    return view('auth.passwords.employer-reset');
	})->name('password.reset');

	//admin password reset routes
    // Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail_e')->name('password.email');
    // Route::post('/password/reset','ResetPasswordController@reset_e');
    // Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm_e')->name('password.request');
    // Route::get('/password/reset/{token}','ResetPasswordController@showResetForm_e')->name('password.reset');
      

});

// ------------------------------ Index (Dashboard)

Route::get('/dashboard', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

Route::post('/ajaxJob', ['as'=>'ajaxJob', 'uses'=>'EmployerController@ajaxJob'])->middleware(['employer', 'auth']);

Route::post('/ajaxReport', ['as'=>'ajaxReport', 'uses'=>'EmployerController@ajaxReport'])->middleware(['employer', 'auth']);

Route::get('/printReport', ['as'=>'employer.printReport', 'uses'=>'EmployerController@printReport'])->middleware(['employer', 'auth']);

// Route::get('/dashboard/{tab}', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

// ------------------------------ Profile

Route::group(['prefix'=>'e/profile', 'as'=>'employerprofile.', 'middleware'=>['employer', 'auth']], function () {
	
	// -------------------- General

	// View Profile
	Route::get('/', ['as'=>'view', 'uses'=>'EmployerController@viewprofile']);

    // View Edit Profile (For New Register User)
	Route::get('/edit', ['as'=>'edit', 'uses'=>'EmployerController@editprofile']);

	// Update Profile
	Route::post('/update', ['as'=>'update', 'uses'=>'EmployerController@updateprofile']);
});


// ------------------------------ Setting

Route::group(['prefix'=>'e/setting', 'as'=>'employersetting.', 'middleware'=>['employer', 'auth']], function () {

	// View Setting

app/Employer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employer extends Model
{
	protected $fillable = [
		'identity_card', 'birth_date', 'race', 'religion', 'current_position', 'employer_type', 'phone',
	];

    public function user() {
        return $this->belongsTo('App\User');
    }
    
	public function jobs() {
		return $this->hasMany('App\Job');
	}
    
    public function company() {
    	return $this->hasOne('App\Company');
    }

    public function applications() {
        return $this->hasMany('App\Application');
    }

}

app/EmployerType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployerType extends Model
{
    protected $fillable = ['name'];
}

resources/views/employer/editprofile.blade.php
@extends('layouts.masterpage')

@section('title')
Update Profile
@endsection

@section('content')
<div class="row">
	<div class="col-12 text-justify">
		<div class="card my-3 p-3">
			<div class="container">
				<form method="post" action="{{route('employerprofile.update')}}">
					{{ csrf_field() }}
					
					{{-- Personal Info --}}
					<div class="row">
						<div class="container">
							<div class="row m-0">
								<h4>Personal Info</h4>
							</div>
							<div class="row">
								<div class="col-lg-2 mb-3"><img src="{{asset('img/profile_picture.jpg')}}" class="img-thumbnail" style="border-radius: 50%;"></div>
								<div class="col-lg-10 m-0">
									<div class="row">
										<div class="col-lg-6 mb-3">
											<i class="fas fa-user-circle"></i>
											<b>
												@if($user->gender == "M")
												{{ $user->firstname }} bin {{ $user->lastname }}
												@else
												{{ $user->firstname }} binti {{ $user->lastname }}
												@endif
											</b>
											@if($user->gender == "M")
											(Male)
											@else
											(Female)
											@endif
										</div>
										<div class="col-lg-6 mb-3">
											<i class="fas fa-envelope"></i> {{ $user->email }}
										</div>
										<div class="col-lg-6">
											<div class="input-group mb-3">
												<div class="input-group-prepend">
													<span class="input-group-text"">I/C Number</span>
												</div>
												<input type="text" class="form-control{{ $errors->has('identity_card') ? ' is-invalid' : '' }}" name="identity_card" placeholder="Update I/C Number" value="{{!empty($user->employer->identity_card)?$user->employer->identity_card:old('identity_card')}}" data-toggle="tooltip" data-placement="right" title="Please fill in only number with no dash (-).">

							                    @if ($errors->has('identity_card'))
							                        <span class="invalid-feedback">
							                            <strong>{{ $errors->first('identity_card') }}</strong>
							                        </span>
							                    @endif
											</div>
										</div>
										<div class="col-lg-6">
											<div class="input-group mb-3">
												<div class="input-group-prepend">
													<span class="input-group-text"">Phone Number</span>
												</div>
												<input type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" placeholder="Update Phone Number" value="{{!empty($user->employer->phone)?$user->employer->phone:old('phone')}}" data-toggle="tooltip" data-placement="right" title="Please fill in only number with no dash (-).">

							                    @if ($errors->has('phone'))
							                        <span class="invalid-feedback">
							                            <strong>{{ $errors->first('phone') }}</strong>
							                        </span>
							                    @endif
											</div>
										</div>
										<div class="col-lg-6">
											<div class="input-group mb-3">
												<div class="input-group-prepend">
													<span class="input-group-text"">Birth Date</span>
												</div>
												<input type="date" class="form-control{{ $errors->has('birth_date') ? ' is-invalid' : '' }}" name="birth_date" placeholder="Update Birth Date" value="{{!empty($user->employer->birth_date)?$user->employer->birth_date:old('birth_date')}}">

							                    @if ($errors->has('birth_date'))
							                        <span class="invalid-feedback">
							                            <strong>{{ $errors->first('birth_date') }}</strong>
							                        </span>
							                    @endif
											</div>
										</div>
										<div class="col-lg-6">
											<div class="input-group mb-3">
												<div class="input-group-prepend">
													<span class="input-group-text"">Race</span>
												</div>

												<select class="form-control{{ $errors->has('race') ? ' is-invalid' : '' }}" name="race">
													<option value="" {{old('race')?'':'selected'}}>Choose Race</option>

													@if(!empty($user->employer->race))
													<option value="Malay" {{old('race')==='Malay'?'selected':$user->employer->race==='Malay'?'selected':''}}>Malay</option>
													<option value="Chinese" {{old('race')==='Chinese'?'selected':$user->employer->race==='Chinese'?'selected':''}}>Chinese</option>
													<option value="Indian" {{old('race')==='Indian'?'selected':$user->employer->race==='Indian'?'selected':''}}>Indian</option>
													<option value="Others" {{old('race')==='Others'?'selected':$user->employer->race==='Others'?'selected':''}}>Others</option>
													@else
													<option value="Malay" {{old('race')==='Malay'?'selected':''}}>Malay</option>
													<option value="Chinese" {{old('race')==='Chinese'?'selected':''}}>Chinese</option>
													<option value="Indian" {{old('race')==='Indian'?'selected':''}}>Indian</option>
													<option value="Others" {{old('race')==='Others'?'selected':''}}>Others</option>
													@endif
												</select>

							                    @if ($errors->has('race'))
							                        <span class="invalid-feedback">
							                            <strong>{{ $errors->first('race') }}</strong>
							                        </span>
							                    @endif
											</div>
										</div>
										<div class="col-lg-6">
											<div class="input-group mb-3">
												<div class="input-group-prepend">
													<span class="input-group-text"">Religion</span>
												</div>

												<select class="custom-select{{ $errors->has('religion') ? ' is-invalid' : '' }}" name="religion">
													<option value="" {{old('religion')?'':'selected'}}>Choose Religion</option>

													@if(!empty($user->employer->race))
													<option value="Islam" {{old('religion')==='Islam'?'selected':$user->employer->religion==='Islam'?'selected':''}}>Islam</option>
													<option value="Christian" {{old('religion')==='Christian'?'selected':$user->employer->religion==='Christian'?'selected':''}}>Christian</option>
													<option value="IndHinduian" {{old('religion')==='Hindu'?'selected':$user->employer->religion==='Hindu'?'selected':''}}>Hindu</option>
													<option value="Buddha" {{old('religion')==='Buddha'?'selected':$user->employer->religion==='Buddha'?'selected':''}}>Buddha</option>
													<option value="Others" {{old('religion')==='Others'?'selected':$user->employer->religion==='Others'?'selected':''}}>Others</option>
													@else
													<option value="Islam" {{old('religion')==='Islam'?'selected':''}}>Islam</option>
													<option value="Christian" {{old('religion')==='Christian'?'selected':''}}>Christian</option>
													<option value="IndHinduian" {{old('religion')==='Hindu'?'selected':''}}>Hindu</option>
													<option value="Buddha" {{old('religion')==='Buddha'?'selected':''}}>Buddha</option>
													<option value="Others" {{old('religion')==='Others'?'selected':''}}>Others</option>
													@endif
												</select>

							                    @if ($errors->has('religion'))
							                        <span class="invalid-feedback">
							                            <strong>{{ $errors->first('religion') }}</strong>
							                        </span>
							                    @endif
											</div>
										</div>
										<div class="col-lg-6"></div>
										<div class="col-lg-6">
											<div class="input-group mb-3">
												<div class="input-group-prepend">
													<span class="input-group-text"">Current Position</span>
												</div>
												<input type="text" class="form-control{{ $errors->has('current_position') ? ' is-invalid' : '' }}" name="current_position" placeholder="Update Current Position" value="{{!empty($user->employer->current_position)?$user->employer->current_position:old('current_position')}}">

							                    @if ($errors->has('current_position'))
							                        <span class="invalid-feedback">
							                            <strong>{{ $errors->first('current_position') }}</strong>
							                        </span>
							                    @endif
											</div>
										</div>
										<div class="col-lg-6">
											<div class="input-group mb-3">
												<div class="input-group-prepend">
													<span class="input-group-text"">Employer Type</span>
												</div>

												<select class="custom-select{{ $errors->has('employer_type') ? ' is-invalid' : '' }}" name="employer_type">
													<option value="" {{old('employer_type')?'':'selected'}}>Choose Employer Type</option>

													@if(!empty($user->employer->employer_type))
													@foreach($employerType as $type)													
													<option value="{{$type->name}}" {{old('employer_type') == $type->name ? 'selected' : $user->employer->employer_type == $type->name ? 'selected' : ''}}>{{$type->name}}</option>
													@endforeach
													@else
													@foreach($employerType as $type)													
													<option value="{{$type->name}}" {{old('employer_type') == $type->name ? 'selected' : ''}}>{{$type->name}}</option>
													@endforeach
													@endif
												</select>

							                    @if ($errors->has('employer_type'))
							                        <span class="invalid-feedback">
							                            <strong>{{ $errors->first('employer_type') }}</strong>
							                        </span>
							                    @endif
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					{{-- Personal Info --}}

					{{-- Button --}}
					<div class="row">
						<div class="col-12">
							<div class="input-group mb-3">
								<button type="submit" class="btn btn-primary ml-auto"><i class="fas fa-save"></i> Update</button>
							</div>
						</div>
					</div>
					{{-- Button --}}

				</form>
			</div>
		</div>
	</div>
</div>

@include('widget.totop')
@endsection

resources/views/employer/editsetting-password.blade.php
@extends('layouts.masterpage')

@section('title')
Change Password
@endsection

@section('content')
<div class="row">
	<div class="container">
		<div class="row m-0">
			<h4>Change Password</h4>
		</div>
		<div class="row m-0">
			<div class="col-12 p-0">
				<form method="POST" action="{{route('employersetting.updatepassword')}}">
					{{csrf_field()}}
					<table class="table">
						<tbody>
							<tr>
								<td>Current Password</td>
								<td>
									<input type="password" class="form-control{{ $errors->has('current_password') || Session::has('check_password') ? ' is-invalid' : '' }}" name="current_password" placeholder="Enter Current Password" required>

		                            @if(Session::has('check_password'))
										<span class="invalid-feedback">
											<strong>{{ session('check_password') }}</strong>
		                                </span>
		                            @endif
		                            @if($errors->has('current_password'))
		                                <span class="invalid-feedback">
		                                	@foreach ($errors->get('current_password') as $message)
												<strong>{{ $message }}</strong>
											@endforeach
		                                </span>
		                            @endif
		                        </td>
							</tr>
							<tr>
								<td>New Password</td>
								<td>
									<input type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" placeholder="Enter New Password" required>
	                            

		                            @if($errors->has('password'))
		                                <span class="invalid-feedback">
		                                	@foreach ($errors->get('password') as $message)
												<strong>{{ $message }}</strong> <br>
											@endforeach                                    
		                                </span>
		                            @endif
								</td>
							</tr>
							<tr>
								<td>New Password Confirmation</td>
								<td>
									<input type="password" class="form-control{{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}" name="password_confirmation" placeholder="New Password Confirmation" required>

		                            @if($errors->has('password_confirmation'))
		                                <span class="invalid-feedback">
		                                	@foreach ($errors->get('password_confirmation') as $message)
												<strong>{{ $message }}</strong>
											@endforeach                                    
		                                </span>
		                            @endif
								</td>

							</tr>
							<tr>
								<td></td>
								<td>
									<button type="submit" id="submit" name="submit" class="btn btn-primary">Change Password</button>
								</td>
							</tr>
						</tbody>
					</table>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/employer/editsetting.blade.php
@extends('layouts.masterpage')

@section('title')
Edit Setting
@endsection

@section('content')
<div class="row">
	<div class="container">
		<div class="row m-0">
			<h4>General Setting</h4>
		</div>
		<div class="row m-0">
			<div class="col-12 p-0">
				<form method="post" action="{{route('employersetting.update')}}">
					{{csrf_field()}}
					<table class="table">
						<tbody>
							<tr>
								<td>First Name</td>
								<td>
									<input type="text" class="form-control{{ $errors->has('firstname') ? ' is-invalid' : '' }}" name="firstname" placeholder="Update first name" value="{{ $user->firstname }}">

		                            @if ($errors->has('firstname'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('firstname') }}</strong>
		                                </span>
		                            @endif
								</td>
							</tr>
							<tr>
								<td>Last Name</td>
								<td>
									<input type="text" class="form-control{{ $errors->has('lastname') ? ' is-invalid' : '' }}" name="lastname" placeholder="Update last name" value="{{ $user->lastname }}">
									
		                            @if ($errors->has('lastname'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('lastname') }}</strong>
		                                </span>
		                            @endif
								</td>
							</tr>
							<tr>
								<td>Gender</td>
								<td>
									<select class="form-control" name="gender">
										@if($user->gender == "M")
											<option value="M" selected>Male</option>
											<option value="F">Female</option>
										@else
											<option value="M">Male</option>
											<option value="F" selected>Female</option>
										@endif
									</select>
								</td>
							</tr>
							<tr>
								<td>Username</td>
								<td>
									<input type="text" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" placeholder="Update username" value="{{ !$errors->has('username') ? $user->username : old('username') }}">
									
		                            @if ($errors->has('username'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('username') }}</strong>
		                                </span>
		                            @endif
		                        </td>
							</tr>
							<tr>
								<td>Email address</td>
								<td>
									<input type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" placeholder="Update email" value="{{ !$errors->has('email') ? $user->email : old('email') }}">
									
		                            @if ($errors->has('email'))
		                                <span class="invalid-feedback">
		                                    <strong>{{ $errors->first('email') }}</strong>
		                                </span>
		                            @endif
								</td>
							</tr>
							<tr>
								<td></td>
								<td><button type="submit" name="submit" class="btn btn-primary"><i class="fas fa-save"></i> Update</button></td>
							</tr>
						</tbody>
					</table>
				</form>
			</div>
		</div>
	</div>
</div>



@endsection

resources/views/employer/viewprofile.blade.php
@extends('layouts.masterpage')

@section('title')
Profile
@endsection

@section('content')
<div class="row">
	<div class="card my-3 p-3">
		<div class="container">
			<div class="row">
				<div class="container">
					<div class="row m-0">
						<h4>Profile</h4> <span class="ml-auto"><a class="btn btn-default btn-sm" href="{{route('employerprofile.edit')}}">Edit</a></span>
					</div>
					<div class="row">
						<div class="col-4 col-lg-2"><img src="{{asset('img/profile_picture.jpg')}}" class="img-thumbnail" style="border-radius: 50%;"></div>
						<div class="col-8 col-lg-10 m-0">
							<div class="row">
								<div class="col-12">
									<i class="fas fa-user-circle"></i>
									<b>
										@if($user->employer->race === 'Malay')
											@if($user->gender == "M")
											{{ $user->firstname }} bin {{ $user->lastname }}
											@else
											{{ $user->firstname }} binti {{ $user->lastname }}
											@endif
										@elseif($user->employer->race === 'Indian')
											@if($user->gender == "M")
											{{ $user->firstname }} A/L {{ $user->lastname }}
											@else
											{{ $user->firstname }} A/P {{ $user->lastname }}
											@endif
										@else
											{{ $user->firstname }} {{ $user->lastname }}
										@endif
									</b>
								</div>
								<div class="col-lg-6">
									@if($user->gender == "M")
									<i class="fas fa-mars"></i> Male
									@else
									<i class="fas fa-venus"></i> Female
									@endif
								</div>
								<div class="col-lg-6">
									<i class="fas fa-id-card"></i> {{ $user->employer->identity_card }}
								</div>
								<div class="col-lg-6">
									<i class="fas fa-envelope"></i> {{ $user->email }}
								</div>
								<div class="col-lg-6">
									<i class="fas fa-phone"></i> {{ $user->employer->phone }}
								</div>
								<div class="col-lg-6">
									<i class="fas fa-birthday-cake"></i> {{ date('d F Y', strtotime($user->employer->birth_date)) }}
								</div>
								<div class="col-lg-6">
									<i class="fas fa-user"></i> {{ $user->employer->race }}
								</div>
								<div class="col-lg-6">
									<i class="fas fa-hand-peace"></i> {{ $user->employer->religion }}
								</div>
								<div class="col-lg-6">
									<i class="fas fa-briefcase"></i> {{ $user->employer->current_position }}
								</div>
								<div class="col-lg-6">
									<i class="fas fa-building"></i> {{ $user->employer->employer_type }}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@include('widget.totop')
@endsection

resources/views/employer/viewsetting.blade.php
@extends('layouts.masterpage')

@section('title')
Setting
@endsection

@section('content')

<div class="row">
	<div class="container">
		<div class="row m-0">
			<h4>General Setting</h4>
			<span class="ml-auto text-right"><a class="btn btn-default btn-sm" href="{{route('employersetting.edit')}}">Edit</a></span>

			<table class="table">
				<tbody>
					<tr>
						<td>Name</td>
						<td class="text-capitalize">
							@if($user->gender == "M")
								{{ $user->firstname }} bin {{ $user->lastname }}
							@else
								{{ $user->firstname }} binti {{ $user->lastname }}
							@endif
							
						</td>
					</tr>
					<tr>
						<td>Gender</td>
						<td>{{ ($user->gender=='M') ? 'Male' : 'Female' }}</td>
					</tr>
					<tr>
						<td>Username</td>
						<td>{{ $user->username }}</td>
					</tr>
					<tr>
						<td>Email</td>
						<td>{{ $user->email }}</td>
					</tr>
					<tr>
						<td>Password</td>
						<td><a class="btn btn-default btn-sm p-0" href="{{route('employersetting.changepassword')}}">Change Password</a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

@endsection