routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ------------------------------------------------------------ 
// ------------------------------------------------------------ Alumni Landing Page
// ------------------------------------------------------------ 

Route::group(['as'=>'alumnihome.'], function() {

	Route::get('/', function () {
	    return view('home.alumni-index');
	})->name('index');

	Route::get('/about-us', function () {
	    return view('home.alumni-aboutus');
	})->name('aboutus');

	Route::get('/event', function () {
	    return view('home.alumni-event');
	})->name('event');

	Route::get('/contact-us', function () {
	    return view('home.alumni-contactus');
	})->name('contactus');

});

// ------------------------------------------------------------ 
// ------------------------------------------------------------ Employer Landing Page
// ------------------------------------------------------------ 

Route::group(['prefix'=>'employer', 'as'=>'employerhome.'], function() {

	Route::get('/index', function () {
	    return view('home.employer-index');
	})->name('index');

	Route::get('/features', function () {
	    return view('home.employer-features');
	})->name('features');

	Route::get('/job-board', function () {
	    return view('home.employer-jobboard');
	})->name('jobboard');

	Route::get('/faqs', function () {
	    return view('home.employer-faqs');
	})->name('faqs');
});

// ------------------------------------------------------------
// ------------------------------------------------------------ Alumni
// ------------------------------------------------------------

// ------------------------------ Login

Auth::routes();

// ------------------------------ Index (Dashboard)

Route::get('/index', [
	'as'=>'alumnidashboard',
	'uses'=>'AlumniController@index'
])->middleware(['alumni', 'auth']);


// ------------------------------ Profile

Route::group(['prefix'=>'a/profile', 'as'=>'alumniprofile.', 'middleware'=>['alumni', 'auth']], function () {
	
	// -------------------- General

	// View Profile
	Route::get('/', [
		'as'=>'view',
		'uses'=>'AlumniController@viewprofile'
	]);

    // View Edit Profile (For New Register User)
	Route::get('/edit', [
		'as'=>'edit',
		'uses'=>'AlumniController@editprofile'
	]);

    // Update Profile (For New Register User)
	Route::post('/update', [
		'as'=>'update',
		'uses'=>'AlumniController@updateprofile'
	]);

	// -------------------- Personal Info

	// View Edit Personal Info
	Route::get('/edit/personal-info', [
		'as'=>'edit.info', 
		'uses'=>'AlumniController@editinfo'
	]);

	// Update Personal Info
	Route::post('/update/personal-info', [
		'as'=>'update.info', 
		'uses'=>'AlumniController@updateinfo'
	]);

	// -------------------- About Me

	// View Edit About Me
	Route::get('/edit/about-me', [
		'as'=>'edit.about', 
		'uses'=>'AlumniController@editabout'
	]);

	// Update About Me
	Route::post('/update/about-me', [
		'as'=>'update.about', 
		'uses'=>'AlumniController@updateabout'
	]);

	// -------------------- Working Experience

	// View Working Experience
	Route::get('/edit/working-experience', [
		'as'=>'view.work', 
		'uses'=>'AlumniController@viewwork'
	]);

	// View Add Working Experience
	Route::get('/add/working-experience', [
		'as'=>'add.work', 
		'uses'=>'AlumniController@addwork'
	]);

	// Save Working Experience
	Route::post('/save/working-experience', [
		'as'=>'save.work', 
		'uses'=>'AlumniController@savework'
	]);

	// View Edit Working Experience
	Route::get('/edit/working-experience/{id}', [
		'as'=>'edit.work', 
		'uses'=>'AlumniController@editwork'
	]);

	// Update Working Experience
	Route::post('/update/working-experience', [
		'as'=>'update.work', 
		'uses'=>'AlumniController@updatework'
	]);

	// Delete Working Experience
	Route::get('/delete/working-experience/{id}', [
		'as'=>'delete.work', 
		'uses'=>'AlumniController@deletework'
	]);

	// -------------------- Education

	// View Education
	Route::get('/edit/education', [
		'as'=>'view.edu', 
		'uses'=>'AlumniController@viewedu'
	]);

	// View Add Education
	Route::get('/add/education', [
		'as'=>'add.edu', 
		'uses'=>'AlumniController@addedu'
	]);

	// Save Education
	Route::post('/save/education', [
		'as' =>'save.edu',
		'uses' =>'AlumniController@saveedu',
	]);

	// View Edit Education
	Route::get('/edit/education/{id}', [
		'as'=>'edit.edu', 
		'uses'=>'AlumniController@editedu'
	]);

	// Update Education
	Route::post('/update/education', [
		'as' =>'update.edu',
		'uses' =>'AlumniController@updateedu'
	]);

	// Delete Education
	Route::get('/delete/education/{id}', [
		'as'=>'delete.edu', 
		'uses'=>'AlumniController@deleteedu'
	]);

	// -------------------- Skills

	// View Skills
	Route::get('/edit/skills-and-expertise', [
		'as'=>'view.skills', 
		'uses'=>'AlumniController@viewskill'
	]);

	// View Add Skills
	Route::get('/add/skills-and-expertise', [
		'as'=>'add.skills', 
		'uses'=>'AlumniController@addskill'
	]);

	// Save Skills
	Route::post('/save/skills-and-expertise', [
		'as'=>'save.skills', 
		'uses'=>'AlumniController@saveskill'
	]);

	// View Edit Skills
	Route::get('/edit/skills-and-expertise/{id}', [
		'as'=>'edit.skills', 
		'uses'=>'AlumniController@editskill'
	]);

	// Update Skills
	Route::post('/update/skills-and-expertise', [
		'as'=>'update.skills', 
		'uses'=>'AlumniController@updateskill'
	]);

	// Delete Skills
	Route::get('/delete/skills-and-expertise/{id}', [
		'as' =>'delete.skills',
		'uses'=>'AlumniController@deleteskill'
	]);

	// -------------------- Language

	// View Language
	Route::get('/edit/language', [
		'as'=>'view.lang', 
		'uses'=>'AlumniController@viewlang'
	]);

	// View Add Language
	Route::get('/add/language', [
		'as'=>'add.lang', 
		'uses'=>'AlumniController@addlang'
	]);

	// Save Language
	Route::post('/save/language', [
		'as'=>'save.lang', 
		'uses'=>'AlumniController@savelang'
	]);

	// View Edit Language
	Route::get('/edit/language/{id}', [
		'as'=>'edit.lang', 
		'uses'=>'AlumniController@editlang'
	]);

	// Update Language
	Route::post('/update/language', [
		'as'=>'update.lang', 
		'uses'=>'AlumniController@updatelang'
	]);

	// Delete Language
	Route::get('/delete/language/{id}', [
		'as'=>'delete.lang', 
		'uses'=>'AlumniController@deletelang'
	]);

});


// ------------------------------ Setting

Route::group(['prefix'=>'a/setting', 'as'=>'alumnisetting.', 'middleware'=>['alumni', 'auth']], function () {

	// View Setting
	Route::get('/', ['as'=>'view', 'uses'=>'AlumniController@viewsetting']);

	// View Edit Setting
	Route::get('/edit', ['as'=>'edit', 'uses'=>'AlumniController@editsetting']);

	// Update Setting
	Route::post('/edit', ['as'=>'update', 'uses'=>'AlumniController@updatesetting']);

	// View Edit Password
	Route::get('/change-password', ['as'=>'changepassword', 'uses'=>'AlumniController@editpassword']);

	// Update Password
	Route::post('/change-password', ['as'=>'updatepassword', 'uses'=>'AlumniController@updatepassword']);

});


// ------------------------------------------------------------
// ------------------------------------------------------------ Employer
// ------------------------------------------------------------

// ------------------------------ Login / Register

Route::group(['prefix'=>'e', 'as'=>'employer.', 'middleware'=>['guest']], function() {

	Route::get('/login', function () {
	    return view('auth.employer-login');
	})->name('login');

	Route::get('/register', function () {
	    return view('auth.employer-register');
	})->name('register');

	Route::get('/password/request', function () {
	    return view('auth.passwords.employer-email');
	})->name('password.request');

	Route::get('/password/reset', function () {
	    return view('auth.passwords.employer-reset');
	})->name('password.reset');

	//admin password reset routes
    // Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail_e')->name('password.email');
    // Route::post('/password/reset','ResetPasswordController@reset_e');
    // Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm_e')->name('password.request');
    // Route::get('/password/reset/{token}','ResetPasswordController@showResetForm_e')->name('password.reset');
      

});

// ------------------------------ Index (Dashboard)

Route::get('/dashboard', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

Route::post('/ajaxJob', ['as'=>'ajaxJob', 'uses'=>'EmployerController@ajaxJob'])->middleware(['employer', 'auth']);

Route::post('/ajaxReport', ['as'=>'ajaxReport', 'uses'=>'EmployerController@ajaxReport'])->middleware(['employer', 'auth']);

Route::get('/printReport', ['as'=>'employer.printReport', 'uses'=>'EmployerController@printReport'])->middleware(['employer', 'auth']);

// Route::get('/dashboard/{tab}', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

// ------------------------------ Profile

Route::group(['prefix'=>'e/profile', 'as'=>'employerprofile.', 'middleware'=>['employer', 'auth']], function () {
	
	// -------------------- General

	// View Profile
	Route::get('/', ['as'=>'view', 'uses'=>'EmployerController@viewprofile']);

    // View Edit Profile (For New Register User)
	Route::get('/edit', ['as'=>'edit', 'uses'=>'EmployerController@editprofile']);

	// Update Profile
	Route::post('/update', ['as'=>'update', 'uses'=>'EmployerController@updateprofile']);
});


// ------------------------------ Setting

Route::group(['prefix'=>'e/setting', 'as'=>'employersetting.', 'middleware'=>['employer', 'auth']], function () {

	// View Setting

resources/views/widget/footer_alumni.blade.php
<footer id="footer" style="background-color: grey;">
	<div class="container">
		<div class="row">
			<div class="col-md mt-5">
				<a href="{{route('alumnihome.index')}}">UTM JOB4U</a>
			</div>
			<div class="col-md mt-5">
				<b>UTM JOB4U</b>
				<ul class="list-group">
					
					<li class="list-group-item">
						<a href="{{route('alumnihome.aboutus')}}">About Us</a>
					</li>
					<li class="list-group-item">
						<a href="{{route('alumnihome.event')}}">Event</a>
					</li>
					<li class="list-group-item">
						<a href="{{route('alumnihome.contactus')}}">Contact Us</a>
					</li>
				</ul>
			</div>
			<div class="col-md mt-5">
				<b>Employer</b>
				<ul class="list-group">
					<li class="list-group-item">Create Free Employer Account</li>
					<li class="list-group-item">
						<a href="{{route('employerhome.index')}}">Employer Center</a>
					</li>
					{{-- <li class="list-group-item">Post a Job</li> --}}
				</ul>
			</div>
			<div class="col-md mt-5">
				<b>Need Help</b>
				<ul class="list-group">
					<li class="list-group-item">FAQ</li>
					<li class="list-group-item">Term of Service</li>
					<li class="list-group-item">Privacy Policy</li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="my-5 mx-auto">
				Copyright © {{ date("Y") }} UTM Job4U | All Right Reserved.
			</div>
		</div>
	</div>
</footer>

resources/views/widget/footer_employer.blade.php
<footer id="footer" style="background-color: grey;">
	<div class="container">
		<div class="row">
			<div class="col-md mt-5">
				<a href="{{route('employerhome.index')}}">UTM JOB4U</a>
			</div>
			<div class="col-md mt-5">
				<b>UTM JOB4U</b>
				<ul class="list-group">
					
					<li class="list-group-item">
						<a href="{{route('alumnihome.aboutus')}}">About Us</a>
					</li>
					<li class="list-group-item">
						<a href="{{route('alumnihome.event')}}">Event</a>
					</li>
					<li class="list-group-item">
						<a href="{{route('alumnihome.contactus')}}">Contact Us</a>
					</li>
				</ul>
			</div>
			<div class="col-md mt-5">
				<b>Employer</b>
				<ul class="list-group">
					<li class="list-group-item">
						<a href="{{route('employerhome.features')}}">Features</a>
					</li>
					<li class="list-group-item">
						<a href="{{route('employerhome.jobboard')}}">Job Boards</a>
					</li>
					@guest
					<li class="list-group-item">
						<a href="{{ route('employer.register') }}">Create Free Employer Account</a>
					</li>
					@endguest
					{{-- <li class="list-group-item">Post a Job</li> --}}
				</ul>
			</div>
			<div class="col-md mt-5">
				<b>Need Help</b>
				<ul class="list-group">
					<li class="list-group-item">
						<a href="{{route('employerhome.faqs')}}">FAQs</a>
					</li>
					<li class="list-group-item">Term of Service</li>
					<li class="list-group-item">Privacy Policy</li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="my-5 mx-auto">
				Copyright © {{ date("Y") }} UTM Job4U | All Right Reserved.
			</div>
		</div>
	</div>
</footer>

resources/views/widget/nav.blade.php
@if(Auth::user()->role_id == 4)
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	
		<div class="container">
            <a class="navbar-brand" href="{{route('employerdashboard')}}">UTM Job4U</a>

		  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarEmployer" aria-controls="navbarAlumni" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>

			<div class="collapse navbar-collapse" id="navbarEmployer">      			
				<ul class="navbar-nav ml-auto
					<li class="nav-item">
						<a class="nav-link" href="{{route('job.post')}}"><button class="btn btn-sm btn-primary">Post a Job</button></a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="iconProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fas fa-cogs fa-lg"></i>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="iconProfile">
							<a class="dropdown-item" href="{{route('company.view')}}"><i class="fas fa-building"></i> Company Profile</a>
							<hr>
							<a class="dropdown-item" href="{{ route('employerprofile.view') }}"><i class="fas fa-user"></i> My Profile</a>
							<a class="dropdown-item" href="{{ route('employersetting.view') }}"><i class="fas fa-cogs"></i> Setting</a>
							<a class="dropdown-item" href="{{ route('logout') }}"
	                           onclick="event.preventDefault();
	                                         document.getElementById('logout-form').submit();">
	                            <i class="fas fa-sign-out-alt"></i> Log Out
	                        </a>

	                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
	                            @csrf
	                        </form>
						</div>
					</li>
				</ul>
			</div>

		</div>
		
	</nav>
@elseif(Auth::user()->role_id == 5)
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	
		<div class="container">
            <a class="navbar-brand" href="{{route('alumnidashboard')}}">UTM Job4U</a>

		  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAlumni" aria-controls="navbarAlumni" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>

			<div class="collapse navbar-collapse" id="navbarAlumni">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{{route('job.top')}}">Top Jobs</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{route('job.categories')}}">Jobs Category</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{route('company.viewtopcompany')}}">Companies</a>
					</li>
				</ul>
	      		<div class="dropdown-divider"></div>
				<ul class="navbar-nav ml-auto">
					{{-- <li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="iconNotification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="fa-layers fa-fw">
								<i class="fas fa-bell fa-lg"></i>
								<span class="fa-layers-counter fa-2x"  style="background:Tomato">1</span>
							</span>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="iconNotification">
							<a class="dropdown-item">Notification 1</a>
							<a class="dropdown-item">Notification 2</a>
							<a class="dropdown-item">Notification 3</a>
						</div>
					</li>
 --}}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="iconProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fas fa-user-circle fa-lg"></i> {{ !empty($user->firstname) ? $user->firstname : Auth::user()->firstname }}
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="iconProfile">
							<a class="dropdown-item" href="{{route('application.viewall')}}"><i class="fas fa-clipboard"></i> Application</a>
							<a class="dropdown-item" href="{{route('application.viewinterview')}}"><i class="fas fa-comment-alt"></i> Interview</a>
							{{-- <a class="dropdown-item" href="#"><i class="fas fa-briefcase"></i> Employment History</a> --}}
							<hr>
							<a class="dropdown-item" href="{{route('alumniprofile.view')}}"><i class="fas fa-user"></i> My Profile</a>
							<a class="dropdown-item" href="{{route('alumnisetting.view')}}"><i class="fas fa-cogs"></i> Setting</a>
							<a class="dropdown-item" href="{{ route('logout') }}"
	                           onclick="event.preventDefault();
	                                         document.getElementById('logout-form').submit();">
	                            <i class="fas fa-sign-out-alt"></i> Log Out
	                        </a>

	                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
	                            @csrf
	                        </form>
						</div>
					</li>
				</ul>
			</div>

		</div>
		
	</nav>
@endif

resources/views/widget/nav_alumni.blade.php
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	
		<div class="container">
            <a class="navbar-brand" href="{{route('alumnihome.index')}}">UTM Job4U</a>
			

		  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAlumni" aria-controls="navbarAlumni" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>

			<div class="collapse navbar-collapse" id="navbarAlumni">
				<ul class="navbar-nav mr-auto">

					<li class="nav-item">
						<a class="nav-link" href="{{route('job.top')}}">Top Jobs</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{route('job.categories')}}">Jobs Category</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{route('company.viewtopcompany')}}">Companies</a>
					</li>
				</ul>
	      		<div class="dropdown-divider"></div>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item mt-1">
						<a class="nav-link" href="{{ route('login') }}">Log In</a>
					</li>
					<li class="nav-item mt-1">
						<a class="nav-link" href="{{ route('register') }}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ route('employerhome.index') }}"><button class="btn btn-sm btn-primary">Employer</button></a>
					</li>
				</ul>

			</div>

		</div>
		
	</nav>

resources/views/widget/nav_employer.blade.php
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	
		<div class="container">
            <a class="navbar-brand" href="{{route('employerhome.index')}}">UTM Job4U</a>
			

		  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAlumni" aria-controls="navbarAlumni" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>

			<div class="collapse navbar-collapse" id="navbarAlumni">
      			
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{{route('employerhome.features')}}">Features</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{route('employerhome.jobboard')}}">Job Boards</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{route('employerhome.faqs')}}">FAQS</a>
					</li>
				</ul>
      			<div class="dropdown-divider"></div>
				<ul class="navbar-nav ml-auto">
					
					<li class="nav-item mt-1">
						<a class="nav-link" href="{{ route('employer.login') }}">Log In</a>
					</li>
					<li class="nav-item mt-1">
						<a class="nav-link" href="{{ route('employer.register') }}">Create Account</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ route('alumnihome.index') }}"><button class="btn btn-sm btn-primary">Alumni</button></a>
					</li>
				</ul>
			</div>

		</div>
		
	</nav>

resources/views/widget/nav_reset.blade.php
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	
		<div class="container">
            <a class="navbar-brand" href="{{route('alumnidashboard')}}">UTM Job4U</a>

		  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAlumni" aria-controls="navbarAlumni" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>

			<ul class="navbar-nav ml-auto">
				
				<li class="nav-item mt-1">
					<a class="nav-link" href="#">RESET PASSWORD</a>
				</li>
			</div>

		</div>
		
	</nav>

resources/views/widget/popup.blade.php
@if(Session::has('success'))
<div id="mdialog" class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <span><b>Success!</b> {{ session('success') }}</span>
</div>
@endif
@if(Session::has('fail'))
<div id="mdialog" class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <span><b>Error!</b> {{ session('fail') }}</span>
</div>
@endif

@php
Session::forget('success');
Session::forget('fail');
@endphp

resources/views/widget/search.blade.php
<div class="row">
	<div class="col">
		<form>
			<div class="input-group">
				<input class="form-control" type="search" placeholder="Search Jobs" aria-label="Search"></input>
				<input class="form-control" type="search" placeholder="Location" aria-label="Search"></input>
				<input class="form-control" type="search" placeholder="Categories" aria-label="Search"></input>
				<div class="input-group-append">
					<button class="btn btn-outline-primary" type="submit"><i class="fas fa-search"></i></button>
				</div>
			</div>
		</form>
	</div>
</div>

resources/views/widget/totop.blade.php
<a href="#bodytop">
	<div class="to-top">
		<i class="fas fa-angle-double-up "></i>
	</div>
</a>