routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ------------------------------------------------------------ 
// ------------------------------------------------------------ Alumni Landing Page
// ------------------------------------------------------------ 

Route::group(['as'=>'alumnihome.'], function() {

	Route::get('/', function () {
	    return view('home.alumni-index');
	})->name('index');

	Route::get('/about-us', function () {
	    return view('home.alumni-aboutus');
	})->name('aboutus');

	Route::get('/event', function () {
	    return view('home.alumni-event');
	})->name('event');

	Route::get('/contact-us', function () {
	    return view('home.alumni-contactus');
	})->name('contactus');

});

// ------------------------------------------------------------ 
// ------------------------------------------------------------ Employer Landing Page
// ------------------------------------------------------------ 

Route::group(['prefix'=>'employer', 'as'=>'employerhome.'], function() {

	Route::get('/index', function () {
	    return view('home.employer-index');
	})->name('index');

	Route::get('/features', function () {
	    return view('home.employer-features');
	})->name('features');

	Route::get('/job-board', function () {
	    return view('home.employer-jobboard');
	})->name('jobboard');

	Route::get('/faqs', function () {
	    return view('home.employer-faqs');
	})->name('faqs');
});

// ------------------------------------------------------------
// ------------------------------------------------------------ Alumni
// ------------------------------------------------------------

// ------------------------------ Login

Auth::routes();

// ------------------------------ Index (Dashboard)

Route::get('/index', [
	'as'=>'alumnidashboard',
	'uses'=>'AlumniController@index'
])->middleware(['alumni', 'auth']);


// ------------------------------ Profile

Route::group(['prefix'=>'a/profile', 'as'=>'alumniprofile.', 'middleware'=>['alumni', 'auth']], function () {
	
	// -------------------- General

	// View Profile
	Route::get('/', [
		'as'=>'view',
		'uses'=>'AlumniController@viewprofile'
	]);

    // View Edit Profile (For New Register User)
	Route::get('/edit', [
		'as'=>'edit',
		'uses'=>'AlumniController@editprofile'
	]);

    // Update Profile (For New Register User)
	Route::post('/update', [
		'as'=>'update',
		'uses'=>'AlumniController@updateprofile'
	]);

	// -------------------- Personal Info

	// View Edit Personal Info
	Route::get('/edit/personal-info', [
		'as'=>'edit.info', 
		'uses'=>'AlumniController@editinfo'
	]);

	// Update Personal Info
	Route::post('/update/personal-info', [
		'as'=>'update.info', 
		'uses'=>'AlumniController@updateinfo'
	]);

	// -------------------- About Me

	// View Edit About Me
	Route::get('/edit/about-me', [
		'as'=>'edit.about', 
		'uses'=>'AlumniController@editabout'
	]);

	// Update About Me
	Route::post('/update/about-me', [
		'as'=>'update.about', 
		'uses'=>'AlumniController@updateabout'
	]);

	// -------------------- Working Experience

	// View Working Experience
	Route::get('/edit/working-experience', [
		'as'=>'view.work', 
		'uses'=>'AlumniController@viewwork'
	]);

	// View Add Working Experience
	Route::get('/add/working-experience', [
		'as'=>'add.work', 
		'uses'=>'AlumniController@addwork'
	]);

	// Save Working Experience
	Route::post('/save/working-experience', [
		'as'=>'save.work', 
		'uses'=>'AlumniController@savework'
	]);

	// View Edit Working Experience
	Route::get('/edit/working-experience/{id}', [
		'as'=>'edit.work', 
		'uses'=>'AlumniController@editwork'
	]);

	// Update Working Experience
	Route::post('/update/working-experience', [
		'as'=>'update.work', 
		'uses'=>'AlumniController@updatework'
	]);

	// Delete Working Experience
	Route::get('/delete/working-experience/{id}', [
		'as'=>'delete.work', 
		'uses'=>'AlumniController@deletework'
	]);

	// -------------------- Education

	// View Education
	Route::get('/edit/education', [
		'as'=>'view.edu', 
		'uses'=>'AlumniController@viewedu'
	]);

	// View Add Education
	Route::get('/add/education', [
		'as'=>'add.edu', 
		'uses'=>'AlumniController@addedu'
	]);

	// Save Education
	Route::post('/save/education', [
		'as' =>'save.edu',
		'uses' =>'AlumniController@saveedu',
	]);

	// View Edit Education
	Route::get('/edit/education/{id}', [
		'as'=>'edit.edu', 
		'uses'=>'AlumniController@editedu'
	]);

	// Update Education
	Route::post('/update/education', [
		'as' =>'update.edu',
		'uses' =>'AlumniController@updateedu'
	]);

	// Delete Education
	Route::get('/delete/education/{id}', [
		'as'=>'delete.edu', 
		'uses'=>'AlumniController@deleteedu'
	]);

	// -------------------- Skills

	// View Skills
	Route::get('/edit/skills-and-expertise', [
		'as'=>'view.skills', 
		'uses'=>'AlumniController@viewskill'
	]);

	// View Add Skills
	Route::get('/add/skills-and-expertise', [
		'as'=>'add.skills', 
		'uses'=>'AlumniController@addskill'
	]);

	// Save Skills
	Route::post('/save/skills-and-expertise', [
		'as'=>'save.skills', 
		'uses'=>'AlumniController@saveskill'
	]);

	// View Edit Skills
	Route::get('/edit/skills-and-expertise/{id}', [
		'as'=>'edit.skills', 
		'uses'=>'AlumniController@editskill'
	]);

	// Update Skills
	Route::post('/update/skills-and-expertise', [
		'as'=>'update.skills', 
		'uses'=>'AlumniController@updateskill'
	]);

	// Delete Skills
	Route::get('/delete/skills-and-expertise/{id}', [
		'as' =>'delete.skills',
		'uses'=>'AlumniController@deleteskill'
	]);

	// -------------------- Language

	// View Language
	Route::get('/edit/language', [
		'as'=>'view.lang', 
		'uses'=>'AlumniController@viewlang'
	]);

	// View Add Language
	Route::get('/add/language', [
		'as'=>'add.lang', 
		'uses'=>'AlumniController@addlang'
	]);

	// Save Language
	Route::post('/save/language', [
		'as'=>'save.lang', 
		'uses'=>'AlumniController@savelang'
	]);

	// View Edit Language
	Route::get('/edit/language/{id}', [
		'as'=>'edit.lang', 
		'uses'=>'AlumniController@editlang'
	]);

	// Update Language
	Route::post('/update/language', [
		'as'=>'update.lang', 
		'uses'=>'AlumniController@updatelang'
	]);

	// Delete Language
	Route::get('/delete/language/{id}', [
		'as'=>'delete.lang', 
		'uses'=>'AlumniController@deletelang'
	]);

});


// ------------------------------ Setting

Route::group(['prefix'=>'a/setting', 'as'=>'alumnisetting.', 'middleware'=>['alumni', 'auth']], function () {

	// View Setting
	Route::get('/', ['as'=>'view', 'uses'=>'AlumniController@viewsetting']);

	// View Edit Setting
	Route::get('/edit', ['as'=>'edit', 'uses'=>'AlumniController@editsetting']);

	// Update Setting
	Route::post('/edit', ['as'=>'update', 'uses'=>'AlumniController@updatesetting']);

	// View Edit Password
	Route::get('/change-password', ['as'=>'changepassword', 'uses'=>'AlumniController@editpassword']);

	// Update Password
	Route::post('/change-password', ['as'=>'updatepassword', 'uses'=>'AlumniController@updatepassword']);

});


// ------------------------------------------------------------
// ------------------------------------------------------------ Employer
// ------------------------------------------------------------

// ------------------------------ Login / Register

Route::group(['prefix'=>'e', 'as'=>'employer.', 'middleware'=>['guest']], function() {

	Route::get('/login', function () {
	    return view('auth.employer-login');
	})->name('login');

	Route::get('/register', function () {
	    return view('auth.employer-register');
	})->name('register');

	Route::get('/password/request', function () {
	    return view('auth.passwords.employer-email');
	})->name('password.request');

	Route::get('/password/reset', function () {
	    return view('auth.passwords.employer-reset');
	})->name('password.reset');

	//admin password reset routes
    // Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail_e')->name('password.email');
    // Route::post('/password/reset','ResetPasswordController@reset_e');
    // Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm_e')->name('password.request');
    // Route::get('/password/reset/{token}','ResetPasswordController@showResetForm_e')->name('password.reset');
      

});

// ------------------------------ Index (Dashboard)

Route::get('/dashboard', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

Route::post('/ajaxJob', ['as'=>'ajaxJob', 'uses'=>'EmployerController@ajaxJob'])->middleware(['employer', 'auth']);

Route::post('/ajaxReport', ['as'=>'ajaxReport', 'uses'=>'EmployerController@ajaxReport'])->middleware(['employer', 'auth']);

Route::get('/printReport', ['as'=>'employer.printReport', 'uses'=>'EmployerController@printReport'])->middleware(['employer', 'auth']);

// Route::get('/dashboard/{tab}', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

// ------------------------------ Profile

Route::group(['prefix'=>'e/profile', 'as'=>'employerprofile.', 'middleware'=>['employer', 'auth']], function () {
	
	// -------------------- General

	// View Profile
	Route::get('/', ['as'=>'view', 'uses'=>'EmployerController@viewprofile']);

    // View Edit Profile (For New Register User)
	Route::get('/edit', ['as'=>'edit', 'uses'=>'EmployerController@editprofile']);

	// Update Profile
	Route::post('/update', ['as'=>'update', 'uses'=>'EmployerController@updateprofile']);
});


// ------------------------------ Setting

Route::group(['prefix'=>'e/setting', 'as'=>'employersetting.', 'middleware'=>['employer', 'auth']], function () {

	// View Setting

app/Alumni.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alumni extends Model
{
    protected $fillable = [
    	'identity_card', 'birth_date', 'birth_state', 'race', 'religion', 'disability', 'marriage_status', 'phone', 'address_1', 'address_2', 'city', 'postal', 'state', 'country', 'about_me', 'profile_view', 'expected_salary'
    ];

    public function user() {
        return $this->belongsTo('App\User');
    }
    
    public function works() {
    	return $this->hasMany('App\Work');
    }

    public function educations() {
    	return $this->hasMany('App\Education');
    }

    public function skills() {
    	return $this->hasMany('App\Skill');
    }

    public function languages() {
        return $this->hasMany('App\Language');
    }

    public function graduate() {
        return $this->hasOne('App\Graduate');
    }

    public function applications() {
        return $this->hasMany('App\Application');
    }
}

resources/views/alumni/editprofile-addedu.blade.php
@extends('layouts.masterpage')

@section('title')
Add Education
@endsection

@section('content')
	<div class="row">
		<div class="container my-2">
			<h4>
				<a href="{{route('alumniprofile.view')}}">Profile</a>
				<i class="fas fa-chevron-right"></i>
				<a href="{{route('alumniprofile.view.edu')}}">Education</a>
				<i class="fas fa-chevron-right"></i>
				Add New
			</h4>

			<form method="post" action="{{route('alumniprofile.save.edu')}}">
				{{ csrf_field() }}
				
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Major</label>
					<div class="col-md-8">
						<input type="text" class="form-control{{ $errors->has('major') ? ' is-invalid' : '' }}" name="major" placeholder="Enter major name" value="{{old('major')}}">

	                    @if ($errors->has('major'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('major') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Education Level</label>
					<div class="col-md-8">
						<select class="form-control{{ $errors->has('education_level') ? ' is-invalid' : '' }}" name="education_level" >
							
							<option value="" {{ old('education_level') ? '' : 'selected' }}>Select education level</option>
							
							@foreach($eduLevel as $level)
								<option value="{{$level->name}}" {{ old('education_level') === $level->name ? 'selected' : '' }} >{{$level->name}}</option>
							@endforeach

						</select>
						
	                    @if ($errors->has('education_level'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('education_level') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Institute</label>
					<div class="col-md-8">
						<input type="text" class="form-control{{ $errors->has('institution') ? ' is-invalid' : '' }}" name="institution" placeholder="Enter institute name">
						
	                    @if ($errors->has('institution'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('institution') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Qualification Level</label>
					<div class="col-md-8">
						<select class="form-control{{ $errors->has('qualification_level') ? ' is-invalid' : '' }}" name="qualification_level" >
							
							<option value="" {{ old('qualification_level') ? '' : 'selected' }}>Select qualification level</option>
							
							@foreach($eduQualificationLevel as $level)
								<option value="{{$level->name}}" {{ old('qualification_level') === $level->name ? 'selected' : '' }} >{{$level->name}}</option>
							@endforeach

						</select>

	                    @if ($errors->has('qualification_level'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('qualification_level') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Graduate</label>
					<div class="col-md-8 input-group">
						<select class="form-control{{ $errors->has('graduate_month') ? ' is-invalid' : '' }}" name="graduate_month">

							<option value="" {{ old('graduate_month') ? '' : 'selected' }}>Select graduation month</option>

							@foreach($months as $month)
								<option value="{{$month}}"  {{ old('graduate_month') === $month ? 'selected' : '' }} >{{$month}}</option>
							@endforeach

						</select>


						<select class="form-control{{ $errors->has('graduate_year') ? ' is-invalid' : '' }}" name="graduate_year" >

							<option value="" {{ old('graduate_year') ? '' : 'selected' }}>Select graduation year</option>

							@for($year = Carbon\Carbon::now()->year; $year > Carbon\Carbon::now()->year-40; $year-=1)
								<option value="{{$year}}" {{ old('graduate_year') == $year ? 'selected' : '' }} >{{$year}}</option>
							@endfor

						</select>

	                    @if ($errors->has('graduate_month'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('graduate_month') }}</strong>
	                        </span>
	                    @endif


	                    @if ($errors->has('graduate_year'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('graduate_year') }}</strong>
	                        </span>
	                    @endif

					</div>
				</div>
				<div class="form-group row">
					<div class="col-md-10 offset-md-2">
						<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/alumni/editprofile-addlang.blade.php
@extends('layouts.masterpage')

@section('title')
Languages
@endsection

@section('content')
	<div class="row">
		<div class="container my-2">
			<h4>
				<a href="{{route('alumniprofile.view')}}">Profile</a>
				<i class="fas fa-chevron-right"></i>
				<a href="{{route('alumniprofile.view.lang')}}">Language</a>
				<i class="fas fa-chevron-right"></i>
				Add New
			</h4>
			<form method="post" action="{{route('alumniprofile.save.lang')}}">
				{{csrf_field()}}
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Language</label>
					<div class="col-md-8">
						<input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Enter Language" name="name" value="{{old('name')}}">

	                    @if ($errors->has('name'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('name') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Proficiency</label>
					<div class="col-md-8">

						<select class="form-control{{ $errors->has('proficiency') ? ' is-invalid' : '' }}" name="proficiency" >

							<option value="" {{ old('proficiency') ? '' : 'selected' }}>Select Proficiency</option>
							
							@foreach($proficiencies as $proficiency)
								<option value="{{$proficiency->name}}" {{ old('proficiency') === $proficiency->name ? 'selected' : '' }} >{{$proficiency->name}}</option>
							@endforeach

						</select>

	                    @if ($errors->has('proficiency'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('proficiency') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<div class="col-md-10 offset-md-2">
						<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/alumni/editprofile-editabout.blade.php
@extends('layouts.masterpage')

@section('title')
Edit About Me
@endsection

@section('content')
<div class="row">
  <div class="container">
    <h4>
      <a href="{{route('alumniprofile.view')}}">Profile</a>
      <i class="fas fa-chevron-right"></i>
      About Me
    </h4>
    <form method="post" action="{{route('alumniprofile.update.about')}}">
      {{ csrf_field() }}
      <div class="form-group">
        <textarea id="summernote" class="form-control{{ $errors->has('about_me') ? ' is-invalid' : '' }}" rows="10" name="about_me">{!! $user->alumni->about_me !!}</textarea>


        @if ($errors->has('about_me'))
            <span class="invalid-feedback">
              <strong>{{ $errors->first('about_me') }}</strong>
            </span>
        @endif

        <div class="row">
          <div class="col"><span id="total-characters">0</span> Words</div>
        </div>
      </div>
      

      <div class="form-group">
        <button type="submit" name="submit" class="btn btn-primary mb-3"><i class="fas fa-save"></i> Update</button>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/alumni/editprofile-viewedu.blade.php
@extends('layouts.masterpage')

@section('title')
Education
@endsection

@section('content')
	<div class="row">
		<div class="container my-2">
			<div class="row">
				<div class="col-9">
					<h4>
						<a href="{{route('alumniprofile.view')}}">Profile</a>
						<i class="fas fa-chevron-right"></i>
						Education
					</h4>
				</div>
				<div class="col-3 text-right">
					<a href="{{route('alumniprofile.add.edu')}}"><button class="btn btn-primary mr-3"><i class="fas fa-plus-circle"></i> Add</button></a>
				</div>
			</div>
			<div class="timeline px-4">
				@if(count($user->alumni->educations) > 0)
					@foreach($user->alumni->educations->sortByDesc('graduate_year') as $edu)
					<div class="timeline-line text-muted "></div>
					<div class='row'>
						<div class="card-group m-3 mx-md-0 w-100">
							<svg class='timeline-icon text-secondary pull-left d-none d-md-block' width="8" height="8" viewBox="0 0 8 8"><path d="M0 0v8l4-4-4-4z" style="fill:#868E96;" transform="translate(2)" /></svg>
							<div class="card">
								<div class="card-body">
									<div class="row">
										<div class="col-md-8">
											<h4 class='text-capitalize'>{{ $edu->major }}</h4>
												<h6 class='small text-muted'><i class="fas fa-book"></i> {{ $edu->education_level }}</h6>
												<h6 class='small text-muted'><i class="fas fa-university"></i> {{ $edu->institution }}</h6>
												<h6 class='small text-muted'><i class="fas fa-check"></i> {{ $edu->qualification_level }}</h6>
												<h6 class='small text-muted'><i class="fas fa-graduation-cap"></i> {{ $edu->graduate_month .' '. $edu->graduate_year}}</h6>
										</div>
										<div class="col-md-4 text-right">
											<a href="{{route('alumniprofile.edit.edu', Crypt::encrypt($edu->id))}}"><button class="btn btn-primary mb-2"><i class="fas fa-edit"></i> Edit</button></a>
											<a href="{{route('alumniprofile.delete.edu', Crypt::encrypt($edu->id))}}" onclick="return confirm('Delete this education?\nWork: {{ $edu->major }}')"><button class="btn btn-danger mb-2"><i class="fas fa-trash-alt"></i> Delete</button></a>
										</div>
									</div>
									
								</div>
							</div>
						</div>
					</div>
					@endforeach
				@else
					<h6><i class="fas fa-search"></i> I'm still searching for education.</h6>
				@endif
			</div>
		</div>
	</div>
@endsection

resources/views/alumni/editprofile-viewlang.blade.php
@extends('layouts.masterpage')

@section('title')
Language
@endsection

@section('content')
	<div class="row">
		<div class="container my-2">
			<h4>
				<a href="{{route('alumniprofile.view')}}">Profile</a>
				<i class="fas fa-chevron-right"></i>
				Language
			</h4>
			<table class="table">
				<thead>
					<tr>
						<th width="50%">Language</th>
						<th width="25%" class="text-right">Proficiency</th>
						<th class="text-right">Action</th>
					</tr>
				</thead>
				<tbody>
					@if(count($user->alumni->languages) > 0)
						@foreach($user->alumni->languages->sortBy('name') as $language)
							<tr>
								<td>{{$language->name}}</td>
								<td class="text-right">{{$language->proficiency}}</td>
								<td class="text-right">
									<a href="{{route('alumniprofile.edit.lang', Crypt::encrypt($language->id))}}"><button class="btn btn-primary"><i class="fas fa-edit"></i> Edit</button></a>

									<a href="{{route('alumniprofile.delete.lang', Crypt::encrypt($language->id))}}" onclick="return confirm('Delete this skills and expertise?\nSkills and Expertise: {{ $language->name }}')"><button class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</button></a>
								</td>
							</tr>
						@endforeach
					@else
						<h6><i class="fas fa-search"></i> I'm still searching for skills.</h6>
					@endif
				</tbody>
			</table>
			<hr class="my-5">
			<h5>Add New Language</h5>
			<form method="post" action="{{route('alumniprofile.save.lang')}}">
				{{csrf_field()}}
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Language</label>
					<div class="col-md-8">
						<input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Enter Language" name="name" value="{{old('name')}}">

	                    @if ($errors->has('name'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('name') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Proficiency</label>
					<div class="col-md-8">

						<select class="form-control{{ $errors->has('proficiency') ? ' is-invalid' : '' }}" name="proficiency" >

							<option value="" {{ old('proficiency') ? '' : 'selected' }}>Select Proficiency</option>
							
							@foreach($proficiencies as $proficiency)
								<option value="{{$proficiency->name}}" {{ old('proficiency') === $proficiency->name ? 'selected' : '' }} >{{$proficiency->name}}</option>
							@endforeach

						</select>

	                    @if ($errors->has('proficiency'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('proficiency') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<div class="col-md-10 offset-md-2">
						<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/alumni/editprofile-viewskills.blade.php
@extends('layouts.masterpage')

@section('title')
Skills & Expertise
@endsection

@section('content')
	<div class="row">
		<div class="container my-2">
			<h4>
				<a href="{{route('alumniprofile.view')}}">Profile</a>
				<i class="fas fa-chevron-right"></i>
				Skills & Expertise
			</h4>
			<table class="table">
				<thead>
					<tr>
						<th width="50%">Skills</th>
						<th width="25%" class="text-right">Proficiency</th>
						<th class="text-right">Action</th>
					</tr>
				</thead>
				<tbody>
					@if(count($user->alumni->skills) > 0)
						@foreach($user->alumni->skills->sortBy('name') as $skill)
							<tr>
								<td>{{$skill->name}}</td>
								<td class="text-right">{{$skill->proficiency}}</td>
								<td class="text-right">
									<a href="{{route('alumniprofile.edit.skills', Crypt::encrypt($skill->id))}}"><button class="btn btn-primary"><i class="fas fa-edit"></i> Edit</button></a>

									<a href="{{route('alumniprofile.delete.skills', Crypt::encrypt($skill->id))}}" onclick="return confirm('Delete this skills and expertise?\nSkills and Expertise: {{ $skill->name }}')"><button class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</button></a>
								</td>
							</tr>
						@endforeach
					@else
						<h6><i class="fas fa-search"></i> I'm still searching for skills.</h6>
					@endif
				</tbody>
			</table>
			<hr class="my-5">
			<h5>Add New Skills</h5>
			<form method="post" action="{{route('alumniprofile.save.skills')}}">
				{{csrf_field()}}
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Skill</label>
					<div class="col-md-8">
						<input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Enter Skills and Expertise" name="name" value="{{old('name')}}">

	                    @if ($errors->has('name'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('name') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Proficiency</label>
					<div class="col-md-8">

						<select class="form-control{{ $errors->has('proficiency') ? ' is-invalid' : '' }}" name="proficiency" >

							<option value="" {{ old('proficiency') ? '' : 'selected' }}>Select Proficiency</option>
							
							@foreach($proficiencies as $proficiency)
								<option value="{{$proficiency->name}}" {{ old('proficiency') === $proficiency->name ? 'selected' : '' }} >{{$proficiency->name}}</option>
							@endforeach

						</select>

	                    @if ($errors->has('proficiency'))
	                        <span class="invalid-feedback">
	                            <strong>{{ $errors->first('proficiency') }}</strong>
	                        </span>
	                    @endif
					</div>
				</div>
				<div class="form-group row">
					<div class="col-md-10 offset-md-2">
						<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
@endsection