routes/web.php
	Route::post('/edit', ['as'=>'update', 'uses'=>'AlumniController@updatesetting']);

	// View Edit Password
	Route::get('/change-password', ['as'=>'changepassword', 'uses'=>'AlumniController@editpassword']);

	// Update Password
	Route::post('/change-password', ['as'=>'updatepassword', 'uses'=>'AlumniController@updatepassword']);

});


// ------------------------------------------------------------
// ------------------------------------------------------------ Employer
// ------------------------------------------------------------

// ------------------------------ Login / Register

Route::group(['prefix'=>'e', 'as'=>'employer.', 'middleware'=>['guest']], function() {

	Route::get('/login', function () {
	    return view('auth.employer-login');
	})->name('login');

	Route::get('/register', function () {
	    return view('auth.employer-register');
	})->name('register');

	Route::get('/password/request', function () {
	    return view('auth.passwords.employer-email');
	})->name('password.request');

	Route::get('/password/reset', function () {
	    return view('auth.passwords.employer-reset');
	})->name('password.reset');

	//admin password reset routes
    // Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail_e')->name('password.email');
    // Route::post('/password/reset','ResetPasswordController@reset_e');
    // Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm_e')->name('password.request');
    // Route::get('/password/reset/{token}','ResetPasswordController@showResetForm_e')->name('password.reset');
      

});

// ------------------------------ Index (Dashboard)

Route::get('/dashboard', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

Route::post('/ajaxJob', ['as'=>'ajaxJob', 'uses'=>'EmployerController@ajaxJob'])->middleware(['employer', 'auth']);

Route::post('/ajaxReport', ['as'=>'ajaxReport', 'uses'=>'EmployerController@ajaxReport'])->middleware(['employer', 'auth']);

Route::get('/printReport', ['as'=>'employer.printReport', 'uses'=>'EmployerController@printReport'])->middleware(['employer', 'auth']);

// Route::get('/dashboard/{tab}', ['as'=>'employerdashboard', 'uses'=>'EmployerController@index'])->middleware(['employer', 'auth']);

// ------------------------------ Profile

Route::group(['prefix'=>'e/profile', 'as'=>'employerprofile.', 'middleware'=>['employer', 'auth']], function () {
	
	// -------------------- General

	// View Profile
	Route::get('/', ['as'=>'view', 'uses'=>'EmployerController@viewprofile']);

    // View Edit Profile (For New Register User)
	Route::get('/edit', ['as'=>'edit', 'uses'=>'EmployerController@editprofile']);

	// Update Profile
	Route::post('/update', ['as'=>'update', 'uses'=>'EmployerController@updateprofile']);
});


// ------------------------------ Setting

Route::group(['prefix'=>'e/setting', 'as'=>'employersetting.', 'middleware'=>['employer', 'auth']], function () {

	// View Setting
	Route::get('/', ['as'=>'view', 'uses'=>'EmployerController@viewsetting']);

	// View Edit Setting
	Route::get('/edit', ['as'=>'edit', 'uses'=>'EmployerController@editsetting']);

	// Update Setting
	Route::post('/edit', ['as'=>'update', 'uses'=>'EmployerController@updatesetting']);

	// View Edit Password
	Route::get('/change-password', ['as'=>'changepassword', 'uses'=>'EmployerController@editpassword']);

	// Update Password
	Route::post('/change-password', ['as'=>'updatepassword', 'uses'=>'EmployerController@updatepassword']);
});


// ------------------------------------------------------------
// ------------------------------------------------------------ Job
// ------------------------------------------------------------

Route::group(['prefix'=>'job', 'as'=>'job.', 'middleware'=>'auth'], function () {

	// For Employer

	Route::get('/post', ['as'=>'post', 'uses'=>'JobController@postjob'])->middleware('employer');

	Route::post('/save', ['as'=>'save', 'uses'=>'JobController@savejob'])->middleware('employer');

	Route::get('/edit/{id}', ['as'=>'edit', 'uses'=>'JobController@editjob'])->middleware('employer');

	Route::post('/update', ['as'=>'update', 'uses'=>'JobController@updatejob'])->middleware('employer');

	Route::get('/overview/{id}', ['as'=>'overview', 'uses'=>'JobController@overview'])->middleware('employer');

	// View

	Route::get('/view/{id}', ['as'=>'view', 'uses'=>'JobController@viewjob']);

	Route::get('/apply/{id}', ['as'=>'apply', 'uses'=>'JobController@applyjob'])->middleware('alumni');

});

Route::group(['prefix'=>'job', 'as'=>'job.'], function () {

	Route::get('/top', ['as'=>'top', 'uses'=>'JobController@viewtopjob']);

	Route::get('/categories', ['as'=>'categories', 'uses'=>'JobController@viewcategoriesjob']);

});

// ------------------------------------------------------------
// ------------------------------------------------------------ Companies
// ------------------------------------------------------------

Route::group(['prefix'=>'company', 'as'=>'company.', 'middleware'=>['auth', 'employer']], function () {


	// For Employer

	Route::get('/profile/view', ['as'=>'view', 'uses'=>'CompanyController@view']);

	Route::get('/profile/add', ['as'=>'add', 'uses'=>'CompanyController@add']);
	
	
	Route::post('/profile/save', ['as'=>'save', 'uses'=>'CompanyController@save']);

	Route::get('/profile/edit', ['as'=>'edit', 'uses'=>'CompanyController@edit']);

	Route::post('/profile/update', ['as'=>'update', 'uses'=>'CompanyController@update']);

});

Route::group(['prefix'=>'company', 'as'=>'company.', 'middleware'=>'auth'], function () {

	// View
	
	Route::get('/profile/{id}', ['as'=>'viewprofile', 'uses'=>'CompanyController@viewprofile']);

});

Route::group(['prefix'=>'company', 'as'=>'company.'], function () {

	Route::get('/top', ['as'=>'viewtopcompany', 'uses'=>'CompanyController@viewtopcompany']);

});

// ------------------------------------------------------------
// ------------------------------------------------------------ Applications
// ------------------------------------------------------------

Route::group(['prefix'=>'application', 'as'=>'application.', 'middleware'=>['auth', 'alumni']], function () {

	// For Alumni


	Route::get('/overview', ['as'=>'viewall', 'uses'=>'ApplicationController@viewall']);

	Route::get('/interview', ['as'=>'viewinterview', 'uses'=>'ApplicationController@viewinterview']);
	
	Route::get('/{id}', ['as'=>'viewapplication', 'uses'=>'ApplicationController@viewapplication']);

	Route::get('/submit/{id}', ['as'=>'submit', 'uses'=>'ApplicationController@submit']);


});

Route::group(['prefix'=>'application', 'as'=>'application.', 'middleware'=>['auth', 'employer']], function () {

	// For Employer
	
	Route::post('/action/{id}/{action}', ['as'=>'action', 'uses'=>'ApplicationController@action']);

	Route::get('/action/{id}/{action}', ['as'=>'action', 'uses'=>'ApplicationController@action']);

	Route::get('/profile/{id}', ['as'=>'viewalumni', 'uses'=>'ApplicationController@viewalumni']);
});

Route::group(['prefix'=>'admin', 'as'=>'admin.', 'middleware'=>['guest']], function () {

	Route::get('/', function() {
		return view('auth.admin-login');
	});

});

Route::get('/admin/print/overall', ['as'=>'admin.printOverallReport', 'uses'=>'AdminController@printOverallReport'])->middleware(['admin', 'auth']);

Route::get('/admin/print/hired', ['as'=>'admin.printHiredReport', 'uses'=>'AdminController@printHiredReport'])->middleware(['admin', 'auth']);

Route::group(['prefix'=>'admin', 'as'=>'admin.', 'middleware'=>['auth', 'admin']], function () {

	// View Dashboard
	Route::get('/dashboard', [
		'as'=>'viewdashboard',
		'uses'=>'AdminController@viewdashboard'
	]);

	// View Setting
	Route::get('/setting', [
		'as'=>'viewsetting',
		'uses'=>'AdminController@viewsetting'
	]);
	Route::get('/setting/edit', [
		'as'=>'editsetting',
		'uses'=>'AdminController@editsetting'
	]);
	Route::post('/setting/update', [
		'as'=>'updatesetting',
		'uses'=>'AdminController@updatesetting'
	]);
	Route::get('/change-password', [
		'as'=>'editpassword',
		'uses'=>'AdminController@editpassword'
	]);
	Route::post('/change-password/update', [
		'as'=>'updatepassword',
		'uses'=>'AdminController@updatepassword'
	]);

	// Graph AJAX
	Route::post('/graphoverallapplication', [
		'as'=>'graphdashboard',
		'uses'=>'AdminController@graphoverallapplication'
	]);

	Route::post('/graphhiredapplication', [
		'as'=>'graphdashboard',
		'uses'=>'AdminController@graphhiredapplication'
	]);

	// View Company
	Route::get('/company/all', [
		'as'=>'viewallcompany',
		'uses'=>'AdminController@viewallcompany'
	]);

	Route::get('/company/verify', [
		'as'=>'listverifycompany',
		'uses'=>'AdminController@listverifycompany'
	]);

	Route::get('/company/view/{id}', [
		'as'=>'viewcompany',
		'uses'=>'AdminController@viewcompany'
	]);

	Route::get('/company/verify/{id}/{action}', [
		'as'=>'verifycompany',
		'uses'=>'AdminController@verifycompany'
	]);

	// View Applications
	Route::get('/application/all', [
		'as'=>'viewallapplication',
		'uses'=>'AdminController@viewallapplication'
	]);

	Route::get('/application/view/{id}', [
		'as'=>'viewapplication',
		'uses'=>'AdminController@viewapplication'
	]);

	// View Job
	Route::get('/job/all', [
		'as'=>'viewalljob',
		'uses'=>'AdminController@viewalljob'
	]);

	Route::get('/job/view/{id}', [
		'as'=>'viewjob',
		'uses'=>'AdminController@viewjob'
	]);

	// View Report
	Route::get('/report/monthly', [
		'as'=>'reportmonthly',
		'uses'=>'AdminController@reportmonthly'
	]);


	Route::get('/report/yearly', [
		'as'=>'reportyearly',
		'uses'=>'AdminController@reportyearly'
	]);

});




// ------------------------------------------------------------
// ------------------------------------------------------------ Error Page
// ------------------------------------------------------------

Route::get('{url}',['as'=>'404','uses'=>'ErrorHandlerController@errorCode404']);

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
    	'name', 'ssm', 'job_category', 'company_type', 'company_size', 'about_us', 'address_1', 'address_2', 'city', 'postal', 'state', 'country', 'dress_code', 'work_days', 'work_hours', 'website_url', 'verification', 'profile_view',
    ];


    public function employer() {
        return $this->belongsTo('App\Employer');
    }
	
	public function jobs() {
    	return $this->hasMany('App\Job');
    }
}

app/CompanyType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyType extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;

use App\Company;
use App\Job;

use App\JobCategory;

use App\CompanyType;
use App\CompanySize;

use Validator;
use Session;

class CompanyController extends Controller
{
    // For Alumni
    
    public function viewtopcompany() {
    	return view('company.viewtopcompany');
    }

    public function viewprofile($id) {
    	$id = Crypt::decrypt($id);
        
    	$company = Company::findOrFail($id);
    	$jobs = Job::all()->where('company_id', $company->id)->where('availability', 2);

    	return view('company.viewprofile', compact(['company', 'jobs']));
    }

    // For Employer

    public function view() {
		$user = Auth::user();

        if(empty($user->employer->company))
            return redirect('/company/profile/add');

		$company = $user->employer->company;
    	
        $jobs = Job::all()->where('company_id', $company->id);

    	return view('company.viewprofile', compact(['company', 'jobs']));
    }
    
    public function add() {
        $user = Auth::user();

        $jobCategories = JobCategory::all();
        $companyTypes = CompanyType::all();
        $companySizes = CompanySize::all();

        if(!empty($user->employer->company))
            return redirect('/company/profile/view');

        return view('company.addprofile', compact(['jobCategories', 'companyTypes', 'companySizes']));
    }

    public function save(Request $request) {
        $employer = Auth::user()->employer;

        $validator = Validator::make($request->all(), [
            'name' => 'required|string',
            'ssm' => 'required|string',
            'job_category' => 'required|string',
            'company_type' => 'required|string',
            'company_size' => 'required|string',
            'about_us' => 'required|string',
            'address_1' => 'required|string',
            'address_2' => 'nullable|string',
            'city' => 'required|string',
            'state' => 'required|string',
            'postal' => 'required|min:5|max:5',
            'country' => 'required|string',
            'dress_code' => 'nullable|string',
            'work_days' => 'required|string',
            'work_hours' => 'required|string',
            'website_url' => 'required|string',
        ]);

        if($validator->fails()) {
            return redirect('/company/profile/add')->withErrors($validator)->withInput();
        }

        if($employer->company()->create($request->all())) {
            return redirect('/company/profile/view')->with('success', 'Company Details is saved!');
        }
        else {
            return redirect('/company/profile/add')->withInput()->with('fail', 'Company Details is not saved!');
        }
    }

    public function edit() {
        $user = Auth::user();

        $company = $user->employer->company;
        $jobCategories = JobCategory::all();
        $companyTypes = CompanyType::all();
        $companySizes = CompanySize::all();

        if(empty($user->employer->company))
            return redirect('/company/profile/add');

        return view('company.editprofile', compact(['company', 'jobCategories', 'companyTypes', 'companySizes']));
    }

    public function update(Request $request) {
        $employer = Auth::user()->employer;

        $validator = Validator::make($request->all(), [
            'name' => 'required|string',
            'ssm' => 'required|string',
            'job_category' => 'required|string',
            'company_type' => 'required|string',
            'company_size' => 'required|string',
            'about_us' => 'required|string',
            'address_1' => 'required|string',
            'address_2' => 'nullable|string',
            'city' => 'required|string',
            'state' => 'required|string',
            'postal' => 'required|min:5|max:5',
            'country' => 'required|string',
            'dress_code' => 'nullable|string',
            'work_days' => 'required|string',
            'work_hours' => 'required|string',
            'website_url' => 'required|string',
        ]);

        if($validator->fails()) {
            return redirect('/company/profile/edit')->withErrors($validator)->withInput();
        }

        // $company = new Company;
        // $company->name = $request->name;
        // $company->ssm = $request->ssm;
        // $company->job_category = $request->job_category;
        // $company->company_type = $request->company_type;
        // $company->company_size = $request->company_size;
        // $company->about_us = $request->about_us;
        // $company->address_1 = $request->address_1;
        // $company->address_2 = $request->address_2;
        // $company->city = $request->city;
        // $company->state = $request->state;
        // $company->postal = $request->postal;
        // $company->country = $request->country;
        // $company->dress_code = $request->dress_code;
        // $company->work_days = $request->work_days;
        // $company->work_hours = $request->work_hours;
        // $company->website_url = $request->website_url;
        // if($employer->company()->update($company)) {

        // dd($request->all());
        if($employer->company()->update($request->except(['_token', 'files']))) {
            return redirect('/company/profile/view')->with('success', 'Company Details is updated!');
        }
        else {
            return redirect('/company/profile/edit')->withInput()->with('fail', 'Company Details is not updated!');
        }
    }

}

resources/views/company/viewprofile.blade.php
@extends('layouts.masterpage')

@section('title')
Company Profile
@endsection

@section('content')

<div class="row">

	{{-- Company Name, Logo, Banner --}}
	<div class="col-12 d-none d-md-block">
		<div class="card bg-dark text-white">
			<img class="card-img" src="{{asset('img/banner.png')}}" alt="Card image">
			<div class="card-img-overlay">
				<div class="row">
					<div class="col-3">
						<img src="{{asset('img/profile_picture.jpg')}}" class="img-thumbnail" style="border-radius: 50%;">
					</div>
					<div class="col">
						<h3>{{$company->name}} <small>({{$company->ssm}})</small></h3>
						<h4>{{$company->job_category}}</h4>
					</div>
					@if(Auth::user()->role_id == 4)
					<div class="col-4 text-right d-none d-lg-block"><a href="{{route('company.edit')}}" class="btn btn-primary">Edit Company Profile</a></div>
					@endif
				</div>
			</div>
		</div>
	</div>

	<div class="col-12 d-block d-md-none text-center">
		<img class="img-thumbnail mb-3" src="{{asset('img/profile_picture.jpg')}}" style="border-radius: 50%;" width="50%">
		<h3>{{$company->name}} <br><small>({{$company->ssm}})</small></h3>
		<h4>{{$company->job_category}}</h4>
		
		@if($company->verification == 0)
		<h6 class="alert alert-secondary mb-0">Unverified</h6>
		@else
		<h6 class="alert alert-success mb-0">Verified</h6>
		@endif

	</div>
	{{-- Company Name, Logo, Banner --}}

	<div class="col-lg-9 order-lg-2">
		<div class="mt-3 d-lg-none d-none d-md-block">
			@if($company->verification == 0)
			<div class="alert alert-secondary">Unverified</div>
			@else
			<div class="alert alert-success">Verified</div>
			@endif
		</div>

		<div class="card mt-3">

			<div class="card-header border-secondary">
				About Us
				@if(Auth::user()->role_id == 4)
				<a href="{{route('company.edit')}}" class="btn btn-sm btn-primary d-block d-lg-none float-right text-white">Edit Company Profile</a>
				@endif
			</div>
			<div class="list-group-item text-justify">
				<p>
					{!!$company->about_us!!}
				</p>
			</div>
			<div class="list-group-item">
				<div class="row">
					<div class="col-lg-4 mb-2"><b>Industry:</b><br>{{$company->job_category}}</div>
					<div class="col-lg-4 mb-2"><b>Company Type:</b><br>{{$company->company_type}}</div>
					<div class="col-lg-4 mb-2"><b>Company Size:</b><br>{{$company->company_size}}</div>
					@if(!empty($company->dress_code))
					<div class="col-lg-4 mb-2"><b>Dress Code:</b><br>{{$company->dress_code}}</div>
					@endif
					<div class="col-lg-4 mb-2"><b>Working Hour:</b><br>{{$company->work_days .', '. $company->work_hours}}</div>
					<div class="col-12"><b>Website:</b><br>{{$company->website_url}}</div>
				</div>
			</div>
			<div class="list-group-item">
				<p><b>Company Address</b></p>
				<ul class="p-0" style="list-style: none;">
					<li>{{$company->address_1}}</li>
					<li>{{$company->address_2}}</li>
					<li>{{$company->postal .', '. $company->city}}</li>
					<li>{{$company->state}}</li>
					<li>{{$company->country}}</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="col-lg-3 order-lg-1">
		<div class="mt-3 d-none d-lg-block">
			@if($company->verification == 0)
			<div class="alert alert-secondary">Unverified</div>
			@else
			<div class="alert alert-success">Verified</div>
			@endif
		</div>
		@if(Auth::user()->role_id == 5)
		<div class="card mt-3">
			<div class="card-header border-secondary">Job Opening</div>
			<div class="list-group-item">
				<ul style="list-style: decimal;">

					@if(!empty($jobs))
					@foreach($jobs as $job)
					<li class="mb-3"><a href="{{route('job.view', Crypt::encrypt($job->id))}}">{{$job->title}}</a> <br><i class="fas fa-map-marker"></i> {{$job->location_city .', '. $job->location_state}}</li>
					@endforeach
					@else
					<li class="mb-3" style="list-style: none;"><i class="fas fa-exclamation"></i> No Job Available</li>
					@endif
				</ul>
			</div>
		</div>
		@endif
	</div>
</div>


@include('widget.totop')
@endsection

resources/views/company/viewtopcompany.blade.php
@extends('layouts.masterpage')

@section('title')
View Top Companies
@endsection

@section('content')
View Top Companies
@endsection